### ISSUE TITLE
How to understand compound words?

### ISSUE THREAD

**Issue by fishfree** [KoichiYasuoka/SuPar-Kanbun#8]
In your paper, 
![image](https://github.com/user-attachments/assets/39f4ee5f-5b2c-48c4-b4b1-fa9d965fd317)
I translated it into Chinese as below:
![image](https://github.com/user-attachments/assets/796d3ea4-e829-4a41-82f3-88fc24ac7830)

I ask this question because I find SuPar-Kanbun models usually tokenize texts into single-character words, which results in many errors for several-characters words:
![image](https://github.com/user-attachments/assets/c7ce0cf3-9386-45cc-9b39-5b902aeb77c0)
I think "梁惠王" should be a single PROPN word.

How can I use your different parsing pipeline sequence and esp. the "compound" mechanism to get better tokenization results?

Many thanks!

**Comment by KoichiYasuoka** [comment]
> I think "梁惠王" should be a single PROPN word.

Sorry but we didn't think so. Since 梁 can be used as a single word. On the other hand 惠王 sometimes refered as a single word or two words, thus we use `compound`. Please follow the discussions (very complicated) on papers below:

* [A Prototyping of Morphological Analyzer for Classical Chinese based on MeCab](http://id.nii.ac.jp/1001/00054940/)
* [Improvement of Morphological Analyzer for Classical Chinese based on MeCab](http://id.nii.ac.jp/1001/00066395/)
* [Refactoring of Wordclasses for Morphological Analysis of Classical Chinese](http://id.nii.ac.jp/1001/00087001/)
* [古典中国語(漢文)の形態素解析](http://hdl.handle.net/2433/217946)
* [Universal Dependencies Parallel Corpora on Classical Chinese, Modern Japanese, and Modern English](http://hdl.handle.net/2433/245218)

**Comment by fishfree** [comment]
@KoichiYasuoka Thank you, Prof.!
In this [paper](https://repository.kulib.kyoto-u.ac.jp/dspace/bitstream/2433/245218/1/IPSJ-CH2019007.pdf):
![image](https://github.com/user-attachments/assets/3f0d739c-28c9-413e-8fe0-cfdb3d7e6c37)
I prefer to the tok/pos result of the Japanese. However, if strictly conforming to the tok/pos specification you made, how can I still use the COMPOUND dependency info for converting to the Japanese result?

Honestly speaking, your tok/pos specification is way far from the common-sense( of contemporary Chinese).

**Comment by KoichiYasuoka** [comment]
> However, if strictly conforming to the tok/pos specification you made, how can I still use the COMPOUND dependency info for converting to the Japanese result?

It's not easy for us yet. We constructed [UD-Kundoku](https://github.com/KoichiYasuoka/UD-Kundoku) but its performance is much worse than [Kanbun-LM](https://github.com/nlp-waseda/Kanbun-LM).

> Honestly speaking, your tok/pos specification is way far from the common-sense( of contemporary Chinese).

Yes, we decided to handle Classical Chinese in different way with Japanese or Modern Chinese under Universal Dependencies, please see [several discussions](https://github.com/UniversalDependencies/UD_Chinese-GSDSimp/issues?q=). If you need other kinds of "tokens" for Classical Chinese, you may make your own models and programs from scratch.
